const findUlEl = document.querySelector('ul');
// console.log(findUlEl);
const findLiEl = document.querySelectorAll('li');
// console.log(findLiEl);
// console.log(findUlEl.firstElementChild);
const lookTextContent = document.querySelector('p');
lookTextContent.textContent = "im look forward";
lookTextContent.style.backgroundColor = "blue";
// console.log(lookTextContent);
const classLook = document.querySelector('.list');
classLook.classList.contains('.list-item');
classLook.classList.add('box');
classLook.classList.remove('list');
classLook.classList.replace('box', 'newBox');
classLook.classList.toggle('paint');
console.log(classLook);
const atrb = document.querySelector('.newBox');
atrb.hasAttribute('a');
atrb.getAttribute('li');
atrb.setAttribute;
console.log(atrb);